name: Deploy

on:
  push:
    branches:
      - dev  # Changed to match your working branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev  # Ensure the correct branch is checked out

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Install composer dependencies
        run: composer install --no-dev

      - name: Install npm packages
        run: npm i

      - name: Semantic release
        id: semantic
        uses: cycjimmy/semantic-release-action@v4
        with:
          semantic_version: 23
          branches: | 
            ['dev']  # Match the branch you're using
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set env
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "RUN_NUMBER=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Build release
        if: steps.semantic.outputs.new_release_published == 'true'
        run: composer run zip

      - name: Release
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.semantic.outputs.new_release_version }}"
          files: |
            dist/send-emails-with-resend.zip
