name: Deploy
on:
  push:
    branches:
      - dev
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.1']
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0  # Required for semantic-release to analyze commit history
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Install composer dependencies
        run: composer install --no-dev
      - name: Install npm packages
        run: npm i
      - name: Build release
        run: composer run zip
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ github.run_number }}"
          files: |
            dist/send-emails-with-resend.zip
